sudo: required

services: docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose run web rails db:create
  - docker-compose run web rails db:migrate
  - docker-compose run web rails test