sudo: required

services: docker

language: ruby

cache: bundler

before_install:
  - docker-compose up --build -d

script:
  - docker-compose run web bundle install
  - docker-compose run web yarn install
  - docker-compose run web rails db:create
  - docker-compose run web rails db:migrate
  - docker-compose run web rails test